        !COMPILER-GENERATED INTERFACE MODULE: Fri May 30 12:00:53 2014
        MODULE CATENARYSYSTEM__genmod
          INTERFACE 
            SUBROUTINE CATENARYSYSTEM(STAGETYPE,NUMLINES,X0,X,F_LINES,  &
     &F_ILINE)
              INTEGER(KIND=4), INTENT(IN) :: NUMLINES
              LOGICAL(KIND=4), INTENT(IN) :: STAGETYPE
              REAL(KIND=8), INTENT(IN) :: X0(6)
              REAL(KIND=8), INTENT(IN) :: X(6)
              REAL(KIND=8), INTENT(OUT) :: F_LINES(6)
              REAL(KIND=8) :: F_ILINE(6)
            END SUBROUTINE CATENARYSYSTEM
          END INTERFACE 
        END MODULE CATENARYSYSTEM__genmod
