        !COMPILER-GENERATED INTERFACE MODULE: Fri May 30 12:00:53 2014
        MODULE SMLLROTTRANS__genmod
          INTERFACE 
            SUBROUTINE SMLLROTTRANS(THETA1,THETA2,THETA3,TRANSMAT)
              REAL(KIND=8), INTENT(IN) :: THETA1
              REAL(KIND=8), INTENT(IN) :: THETA2
              REAL(KIND=8), INTENT(IN) :: THETA3
              REAL(KIND=8), INTENT(OUT) :: TRANSMAT(3,3)
            END SUBROUTINE SMLLROTTRANS
          END INTERFACE 
        END MODULE SMLLROTTRANS__genmod
